#!/bin/bash
# Mac Cleanup Script - Interactive & Safe
# Generated by mac-audit skill
# Run: bash ~/.claude/skills/mac-audit/cleanup.sh
# Non-interactive: bash cleanup.sh --yes

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse arguments
AUTO_YES=false
for arg in "$@"; do
    case $arg in
        -y|--yes)
            AUTO_YES=true
            shift
            ;;
    esac
done

# Tracking
TOTAL_FREED=0

echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║      Mac Cleanup Script v1.1.0         ║${NC}"
echo -e "${BLUE}║      Interactive & Safe                ║${NC}"
if $AUTO_YES; then
    echo -e "${BLUE}║      Mode: AUTO (--yes)                ║${NC}"
fi
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
echo ""

confirm() {
    local prompt="$1"
    local default="${2:-n}"

    # Auto-yes mode: skip prompts
    if $AUTO_YES; then
        echo -e "${prompt} ... ${GREEN}auto-confirmed${NC}"
        return 0
    fi

    # Non-TTY mode: skip prompts (default no)
    if [[ ! -t 0 ]]; then
        echo -e "${prompt} ... ${YELLOW}skipped (no TTY)${NC}"
        return 1
    fi

    if [[ "$default" == "y" ]]; then
        prompt="$prompt [Y/n]: "
    else
        prompt="$prompt [y/N]: "
    fi

    read -p "$prompt" response
    response=${response:-$default}
    [[ "$response" =~ ^[Yy]$ ]]
}

get_size() {
    local path="$1"
    if [[ -d "$path" ]]; then
        du -sh "$path" 2>/dev/null | awk '{print $1}' || echo "0"
    else
        echo "0"
    fi
}

# ============================================
# SAFE CLEANUPS (Caches only)
# ============================================
echo -e "${GREEN}═══ SAFE CLEANUPS (Caches) ═══${NC}"
echo ""

# Homebrew
if command -v brew &> /dev/null; then
    size=$(brew cleanup -n 2>&1 | grep "approximately" | awk '{print $5$6}' || echo "unknown")
    if confirm "Clean Homebrew cache (~$size)?"; then
        brew cleanup
        echo -e "${GREEN}✓ Homebrew cleaned${NC}"
    fi
fi

# UV cache
if [[ -d ~/.cache/uv ]]; then
    size=$(get_size ~/.cache/uv)
    if confirm "Clean UV cache (~$size)?"; then
        uv cache clean 2>/dev/null || rm -rf ~/.cache/uv
        echo -e "${GREEN}✓ UV cache cleaned${NC}"
    fi
fi

# pip cache
if [[ -d ~/.cache/pip ]] || [[ -d ~/Library/Caches/pip ]]; then
    size=$(du -sh ~/.cache/pip ~/Library/Caches/pip 2>/dev/null | awk '{sum+=$1} END {print sum"M"}' || echo "unknown")
    if confirm "Clean pip cache (~$size)?"; then
        pip cache purge 2>/dev/null || true
        rm -rf ~/.cache/pip ~/Library/Caches/pip 2>/dev/null || true
        echo -e "${GREEN}✓ pip cache cleaned${NC}"
    fi
fi

# npm cache
if [[ -d ~/.npm/_cacache ]]; then
    size=$(get_size ~/.npm/_cacache)
    if confirm "Clean npm cache (~$size)?"; then
        npm cache clean --force 2>/dev/null
        echo -e "${GREEN}✓ npm cache cleaned${NC}"
    fi
fi

# yarn cache
if [[ -d ~/.yarn/cache ]]; then
    size=$(get_size ~/.yarn/cache)
    if confirm "Clean yarn cache (~$size)?"; then
        yarn cache clean 2>/dev/null
        echo -e "${GREEN}✓ yarn cache cleaned${NC}"
    fi
fi

echo ""

# ============================================
# MODERATE CLEANUPS (Review recommended)
# ============================================
echo -e "${YELLOW}═══ MODERATE CLEANUPS ═══${NC}"
echo ""

# Docker
if command -v docker &> /dev/null; then
    docker_size=$(docker system df 2>/dev/null | awk 'NR>1 {sum+=$4} END {print sum}' || echo "0")
    if confirm "Prune Docker (images, containers, volumes)?"; then
        docker system prune -a --volumes -f
        echo -e "${GREEN}✓ Docker pruned${NC}"
    fi
fi

# Xcode DerivedData
if [[ -d ~/Library/Developer/Xcode/DerivedData ]]; then
    size=$(get_size ~/Library/Developer/Xcode/DerivedData)
    if confirm "Clean Xcode DerivedData (~$size)?"; then
        rm -rf ~/Library/Developer/Xcode/DerivedData/*
        echo -e "${GREEN}✓ Xcode DerivedData cleaned${NC}"
    fi
fi

# iOS Simulators
if command -v xcrun &> /dev/null; then
    sim_count=$(xcrun simctl list devices unavailable 2>/dev/null | grep -c "unavailable" 2>/dev/null || echo 0)
    sim_count=$(echo "$sim_count" | tr -d '[:space:]')
    if [[ "$sim_count" =~ ^[0-9]+$ ]] && [[ "$sim_count" -gt 0 ]]; then
        if confirm "Delete $sim_count unavailable iOS simulators?"; then
            xcrun simctl delete unavailable
            echo -e "${GREEN}✓ Old simulators deleted${NC}"
        fi
    fi
fi

# Time Machine local snapshots
tm_count=$(tmutil listlocalsnapshots / 2>/dev/null | wc -l | tr -d ' ')
if [[ "$tm_count" -gt 5 ]]; then
    if confirm "Delete $tm_count Time Machine local snapshots?" "n"; then
        tmutil deletelocalsnapshots /
        echo -e "${GREEN}✓ TM snapshots deleted${NC}"
    fi
fi

echo ""

# ============================================
# SYSTEM MAINTENANCE
# ============================================
echo -e "${BLUE}═══ SYSTEM MAINTENANCE ═══${NC}"
echo ""

# Flush DNS
if confirm "Flush DNS cache?"; then
    sudo dscacheutil -flushcache
    sudo killall -HUP mDNSResponder 2>/dev/null || true
    echo -e "${GREEN}✓ DNS cache flushed${NC}"
fi

# Purge memory
if confirm "Purge inactive memory?"; then
    sudo purge
    echo -e "${GREEN}✓ Memory purged${NC}"
fi

echo ""

# ============================================
# REVIEW SECTION (Manual intervention)
# ============================================
echo -e "${RED}═══ ITEMS FOR MANUAL REVIEW ═══${NC}"
echo ""

# Homebrew orphans
echo -e "${YELLOW}Homebrew packages that may be orphaned:${NC}"
brew autoremove -n 2>/dev/null | head -5 || echo "None found"
echo ""

# Large caches
echo -e "${YELLOW}Largest caches in ~/Library/Caches:${NC}"
du -sh ~/Library/Caches/* 2>/dev/null | sort -hr | head -5
echo ""

# Login items
echo -e "${YELLOW}Login items (consider removing unused):${NC}"
osascript -e 'tell application "System Events" to get name of login items' 2>/dev/null || echo "Check System Settings"
echo ""

# ============================================
# SUMMARY
# ============================================
echo -e "${GREEN}╔════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║           Cleanup Complete!            ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════╝${NC}"
echo ""
echo "Run 'df -h /' to see current disk usage."
echo ""
